name: image:dev Builder
on:
  push:
    branches:
      - dev
      
jobs:
  push:
    name: "image:dev"
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '!norun') }}
    strategy:
      fail-fast: false
          
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          ref: dev
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v3.3.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
             ghcr.io/multiegg/image:base
