name: image:base Builder
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"
      
jobs:
  push:
    name: "image:base"
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '!norun') }}
    strategy:
      fail-fast: false
          
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v3.3.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
             ghcr.io/multiegg/image:base
  dispatch:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Main Image Build
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REGISTRY_TOKEN }}
          repository: multiegg/image
          event-type: base-image-built
